AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.13

  Sample SAM Template for HpSpider313

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    MemorySize: 512

Resources:
  HpSpiderFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hp_spider
      DockerTag: python3.13-v1

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  HpSpiderFunction:
    Description: HpSpider Lambda Function ARN
    Value: !GetAtt HpSpiderFunction.Arn
  HpSpiderFunctionIamRole:
    Description: Implicit IAM Role created for HpSpider function
    Value: !GetAtt HpSpiderFunctionRole.Arn
